In [41]:
import torch
print(torch.__version__)

2.7.1+cpu


## Introduction To Creating Tensors

In [42]:
# Scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [43]:
scalar.ndim

0

In [44]:
# Vector
vector = torch.tensor([7,7])
print(vector)

tensor([7, 7])


In [45]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [46]:
#Matrix
matrix = torch.tensor([[7,7],[7,7]])
print(matrix)

tensor([[7, 7],
        [7, 7]])


In [47]:
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([2, 2])


In [48]:
#Tensor
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
print(tensor)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [49]:
print(tensor.ndim)
print(tensor.shape)

3
torch.Size([1, 3, 3])


### Random Tensors

In [50]:
random_tensors = torch.rand(3,4)
print(random_tensors)

tensor([[0.4937, 0.9944, 0.2856, 0.7450],
        [0.1173, 0.0944, 0.4894, 0.5514],
        [0.1409, 0.1899, 0.7393, 0.1323]])


In [51]:
random_tensors.ndim

2

In [52]:
# Create a Random tensor with similar shape to image
random_tensor_image = torch.rand(size=(3,224,224))
random_tensor_image.ndim,random_tensor_image.shape

(3, torch.Size([3, 224, 224]))

### Zeros and Ones Tensors

In [53]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range tensors and tensors-like

In [55]:
one_to_zero = torch.arange(start=1,end=11,step=1)
one_to_zero

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
# creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_zero)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [57]:
float_32_type = torch.tensor([3.,6.,9.],dtype=None)

In [58]:
float_32_type,float_32_type.dtype

(tensor([3., 6., 9.]), torch.float32)

### Matrix Multiplication

In [59]:
# element wise Multiplication
ele_tensor = torch.tensor([1,2,3])
ele_tensor * 10

tensor([10, 20, 30])

In [60]:
#Matrix Multiplication(Dot-Product)
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [61]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [62]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")



Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (aggregation)

In [63]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [65]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [67]:
x.dtype

torch.int64

In [72]:
# mean requires tensor as an float 32 as input
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [73]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [76]:
torch.argmin(x),x.argmin()

(tensor(0), tensor(0))

In [78]:
torch.argmax(x),x.argmax()

(tensor(9), tensor(9))

### Reshaping,Stacking,Squeezing,Unsqueezing tensors

In [92]:
# Reshape
x_shape = torch.arange(1.,10)
x_shape,x_shape.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [93]:
x_shape_reshaped = x_shape.reshape(1,9)
x_shape_reshaped,x_shape_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [94]:
z_view = x_shape.view(1,9)
z_view,z_view.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [95]:
# If z changes x is also changes
z_view[:,0] = 5
z_view,x_shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [99]:
stacked = torch.stack([x_shape,x_shape,x_shape,x_shape],dim=1)
stacked,stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [ ]:
#torch.squeeze() (I remember this as squeezing the tensor to only have dimensions over 1)
print(f"Previous tensor: {x_shape_reshaped}")
print(f"Previous shape: {x_shape_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_shape_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [101]:
#torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [102]:
#torch.permute(input, dims), where the input gets turned into a view with new dims.

# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [105]:
x_original[0,0,0] = 1234
x_original[0,0,0],x_permuted[0,0,0]

(tensor(1234.), tensor(1234.))

### Indexing (selecting data from tensors)

In [106]:
x_index = torch.arange(1, 10).reshape(1, 3, 3)
x_index, x_index.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [107]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x_index[0]}") 
print(f"Second square bracket: {x_index[0][0]}") 
print(f"Third square bracket: {x_index[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


### PyTorch tensors & NumPy

In [108]:
import numpy as np